main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

login:
    path: /login
    defaults:
        _controller: MainBundle:User:login

login_check:
    path: /login_check

logout:
    path: /logout