#Anonym routes
main_homepage:
    path: /
    defaults:
        _controller: MainBundle:Default:index

main_post_add:
    path: /post/add
    defaults:
        _controller: MainBundle:Post:add

#User routes
main_user:
    path: /user
    defaults:
        _controller: MainBundle:Default:indexUser

#Admin routes
main_admin:
    path: /admin
    defaults:
        _controller: MainBundle:Default:indexAdmin

main_register:
    path : /register
    defaults:
        _controller: MainBundle:User:register
