#Anonym routes
main_homepage:
    path: /
    defaults:
        _controller: MainBundle:Default:index

main_post_add:
    path: /post/add
    defaults:
        _controller: MainBundle:Post:add

main_register:
    path: /register
    defaults:
        _controller: MainBundle:User:register

main_register_check:
    path: /register/check/{check}/{id}
    defaults:
        _controller: MainBundle:User:checkRegistration
    requirements:
        id: '\d+'

#User routes
main_user:
    path: /user
    defaults:
        _controller: MainBundle:Default:indexUser

main_my_profile:
    path: /user/profile
    defaults:
        _controller: MainBundle:User:profile

main_user_profile:
    path: /user/profile/{id}
    defaults:
        _controller: MainBundle:User:profile
    requirements:
        id: '\d+'

main_user_profile_page:
    path: /user/profile/{id}/{page}
    defaults:
        _controller: MainBundle:User:profile
    requirements:
        id: '\d+'
        page: '\d+'

main_user_post_delete:
    path: /user/post/delete/{id}
    defaults:
        _controller: MainBundle:Post:delete
    requirements:
        id: '\d+'

main_user_post_edit:
    path: /user/post/edit/{id}
    defaults:
        _controller: MainBundle:Post:add
    requirements:
        id: '\d+'

#Admin routes
main_admin:
    path: /admin
    defaults:
        _controller: MainBundle:Default:indexAdmin

main_admin_page:
    path: /admin/{page}-{page2}
    defaults:
        _controller: MainBundle:Default:indexAdmin
    requirements:
        page: '\d+'
        page2: '\d+'

main_admin_delete_user:
    path: /admin/user/delete/{id}
    defaults:
        _controller: MainBundle:User:delete