#Anonym routes
main_homepage:
    path: /
    defaults:
        _controller: MainBundle:Default:index

main_post_add:
    path: /post/add
    defaults:
        _controller: MainBundle:Post:add

main_register:
    path: /register
    defaults:
        _controller: MainBundle:User:register

main_register_check:
    path: /register/check/{check}/{id}
    defaults:
        _controller: MainBundle:User:checkRegistration
    requirements:
        id: '\d+'

#User routes
main_user:
    path: /user
    defaults:
        _controller: MainBundle:Default:indexUser

main_user_profile:
    path: /user/profile
    defaults:
        _controller: MainBundle:User:profile

main_user_profile_page:
    path: /user/profile/page/{page}
    defaults:
        _controller: MainBundle:User:profile
    requirements:
            page: '\d+'

main_user_profile_id:
    path: /user/profile/{id}
    defaults:
        _controller: MainBundle:User:profileById
    requirements:
        id: '\d+'

#Admin routes
main_admin:
    path: /admin
    defaults:
        _controller: MainBundle:Default:indexAdmin
