main_homepage:
    path: /
    defaults:
        _controller: MainBundle:Default:index

main_user:
    path : /user
    defaults:
        _controller: MainBundle:User:index

main_post:
    path : /post
    defaults:
        _controller: MainBundle:Post:index
